# Generated by Django 4.2.2 on 2023-06-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_status_remove_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
