# Generated by Django 4.2.2 on 2023-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_checkoutaddress_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='product',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='Order Placed', max_length=100),
        ),
    ]
