# Generated by Django 4.2.2 on 2023-06-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_order_product_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
