# Generated by Django 4.2.2 on 2023-06-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forget_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
