# Generated by Django 4.2.1 on 2023-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_orderitem_status_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='Order Placed', max_length=100),
        ),
    ]
