# Generated by Django 4.2.1 on 2023-06-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_product_status_checkoutaddress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='status',
        ),
    ]
